const DEFAULT_PRIVACY_POLICY_JSON = {
  introduction: "This Privacy Policy applies to the digital ministry platforms operated by Joshua Generation Ministry under the spiritual leadership of Apostle Joshua Iyemifokhae. This includes our website, mobile interface, streaming services (Radio and Podcast), newsletter distributions, digital libraries, and online donation channels.\n\nBy visiting our website or using any of our resources, you agree to the collection, use, and handling of information as described in this policy. We prioritize your privacy and will never sell or exploit your data.",
  
  collection: "To provide a tailored spiritual growth experience and support our operations, we collect the following types of information:\n\nA. Personal Information: Names, email addresses, phone numbers, and optional prayer request information that you provide when subscribing to devotionals, asking for prayers, or registering as a partner.\n\nB. Donation & Payment Data: We collect billing names and transaction records for transparency. All credit card or banking details are processed through secure, PCI-DSS compliant payment gateways (e.g. Stripe, Selar, or Flutterwave). We do not store your financial details.\n\nC. Technical & Interaction Logs: IP addresses, browser details, page interactions, radio player stream metrics, audio buffering latency, and digital book progress. This helps us ensure server stability and app performance.\n\nD. Notification Settings: Preferences regarding push notifications, daily devotional timings, and newsletter topics.",
  
  usage: "The data we collect is strictly used to serve our community, including:\n\n* Spiritual Resources: Sending your daily devotionals, newsletter digests, and keeping your book reading progress active.\n* Partnerships & Donations: Securing, tracking, and confirming your seeds and partnership declarations.\n* Live Broadcasts: Maintaining connections to our Mixlr radio embed and podcasts, and notifying you when Apostle Joshua Iyemifokhae is live.\n* Continuous Improvement: Identifying server errors, speeding up book resource rendering, and refining navigation flow based on analytics.\n* Security & Anti-Fraud: Authenticating administrator sessions and blocking abusive attempts on our forms and portals.",
  
  protection: "We recognize our responsibility to protect your digital presence.\n\nCore Commitment: Joshua Generation will never sell, lease, rent, or trade your personal details to advertising agencies, lists, or commercial companies.\n\nInformation is only shared under these strict circumstances:\n\n* Service Providers: Sharing details with specialized companies facilitating payment gateways (e.g. Stripe, Selar), database persistence (e.g. Supabase, PostgreSQL host), or newsletter distribution (e.g. Mailchimp, SendGrid) solely to perform actions on our behalf.\n* Legal Requirement: When obliged to comply with lawful warrants, court orders, or regulations.",
  
  cookies: "We utilize cookies and standard web storage objects to maintain session credentials, remember volume settings on our audio players, store cache data, and recognize your device for secure admin dashboard entry.\n\nFor in-depth details on cookie categories and opt-out routes, please view our comprehensive Cookie Policy.",
  
  rights: "You are in control of your personal data. You possess the right to:\n\n* Access & Copy: Request details of the personal data we hold about you.\n* Update & Edit: Request corrections to any outdated or inaccurate name, email, or telephone listings.\n* Erasure (Right to be Forgotten): Request the full deletion of your record, including subscription listings.\n* Opt-Out: Click the \"Unsubscribe\" button in any newsletter email to halt further updates instantly.",
  
  contact: "For any privacy questions, security concerns, data deletion requests, or explanations of how we protect your personal information, please reach out to our privacy administration:\n\nJoshua Generation Administration\nEmail: hello@joshuagen.org\nResponse Window: 24 - 48 Hours"
};

const DEFAULT_TERMS_OF_SERVICE_JSON = {
  acceptance: "These Terms of Service govern your access to and use of the website joshuageneration.com, including all audio streams, digital literature libraries, daily devotional newsletters, admin control suites, and donation systems.\n\nBy accessing, browsing, downloading books, or registering an account, you affirm that you have read, understood, and agreed to be legally bound by these terms. If you do not agree, please discontinue using our digital platforms.",
  
  offerings: "Joshua Generation is a digital ministry offering gospel teachings, prayer platforms, and faith-building publications. Services provided include:\n\n* Sermon Streams: On-demand sermon audio and video playback, and live radio broadcasting via Mixlr embeddings.\n* Books Library: Interactive online reading panel and download portals for books authored by Apostle Joshua Iyemifokhae.\n* Devotional Newsletter: Subscription-based messages and prayer updates.\n* Prayer Wall: Community boards to share testimonies and intercessory prayer requests.\n\nWe reserve the right to modify, suspend, or restrict any segment of these offerings at our discretion and without prior notice.",
  
  downloads: "All digital books, devotional studies, and sermon outlines offered on the site are protected by copyright. When you download a digital book:\n\nPersonal & Small Group License Only: You are granted a non-exclusive, non-transferable, revocable license to access and read the books for personal development or small group study. You may not print copies for commercial resale, translate the material without written permission, or publish files on other public file shares.",
  
  giving: "Partnership pledges and seed sowings support missions, local church building, charity outreaches, and digital broadcasting equipment.\n\n* Voluntary Contributions: All monetary donations, seed sowings, and partnership contributions made online or through third-party platforms are entirely voluntary.\n* Refund Policy: In line with standard charitable giving rules, all sowings and partnership gifts represent irreversible donations to the ministry and are non-refundable.\n* Secure Payment: You agree to provide true, accurate, and authorized credit card or bank details to our payment gateway. We are not liable for transaction errors caused by third-party processors.",
  
  conduct: "As a faith-based digital sanctuary, we maintain a standard of respect, kindness, and spiritual integrity. Users agree not to:\n\n* Post spam, advertising, or promotional solicitations on the Prayer Wall or comments.\n* Harass, insult, or post hateful comments targeting other community members.\n* Attempt to bypass administration login parameters, execute DDoS attacks, or inject malicious scripts.\n* Impersonate Apostle Joshua Iyemifokhae, Joshua Generation ministry leaders, or administrators.\n\nViolations will result in permanent suspension of access and IP ban without warning.",
  
  copyright: "The logo, design components, site illustrations, audio tracks, written daily devotionals, sermons, and digital books are the exclusive property of Joshua Generation Ministry and Apostle Joshua Iyemifokhae.\n\nYou may not duplicate, copy, screen-record, edit, or modify any media assets from this website for use in commercial applications or other ministry websites without express written consent.",
  
  disclaimer: "Our services, sermons, broadcasts, and literature are provided on an \"as is\" and \"as available\" basis, without any warranties of any kind, whether express or implied.\n\nJoshua Generation Ministry, including its leaders, speakers, volunteers, and technical developers, will not be liable for any direct or indirect damages resulting from: network outages, loss of audio playback sync, data breaches via third-party libraries, book download download failure, or reliance on information presented within devotionals and blogs.",
  
  governing: "These Terms of Service are governed by and construed in accordance with the laws of the jurisdiction in which the ministry is headquarted, without regard to conflict of laws principles.\n\nAny dispute arising from these terms or your use of this digital portal shall be resolved through friendly dialogue first. If unresolved, disputes will be settled within local arbitration tribunals."
};

export const DEFAULT_PRIVACY_POLICY = JSON.stringify(DEFAULT_PRIVACY_POLICY_JSON);
export const DEFAULT_TERMS_OF_SERVICE = JSON.stringify(DEFAULT_TERMS_OF_SERVICE_JSON);
